import { create } from 'zustand'
import { persist } from 'zustand/middleware'

export type Lang = 'en' | 'uz' | 'ru'

export const LANGUAGES: { code: Lang; label: string; flag: string }[] = [
  { code: 'en', label: 'English',    flag: '🇬🇧' },
  { code: 'uz', label: "O'zbekcha",  flag: '🇺🇿' },
  { code: 'ru', label: 'Русский',    flag: '🇷🇺' },
]

// ── Translations ─────────────────────────────────────────────
export const T = {
  en: {
    // Nav
    dashboard:   'Dashboard',
    pos:         'POS',
    products:    'Products',
    inventory:   'Inventory',
    customers:   'Customers',
    orders:      'Orders',
    finance:     'Finance',
    marketing:   'Marketing',
    sellers:     'Sellers',
    branches:    'Branches',
    settings:    'Settings',
    // Common
    save:        'Save',
    cancel:      'Cancel',
    edit:        'Edit',
    delete:      'Delete',
    add:         'Add',
    search:      'Search',
    loading:     'Loading…',
    noData:      'No data found',
    confirm:     'Are you sure?',
    // Products
    addProduct:  'Add Product',
    productName: 'Product Name',
    brand:       'Brand',
    category:    'Category',
    skuBase:     'SKU Base',
    costPrice:   'Cost Price',
    sellPrice:   'Sell Price',
    description: 'Description',
    variants:    'Variants',
    initialStock:'Initial Stock',
    // Sellers
    addSeller:   'Add Seller',
    sellerName:  'Full Name',
    email:       'Email',
    role:        'Role',
    branch:      'Branch',
    password:    'Password',
    pin:         'PIN',
    // Branches
    addBranch:   'Add Branch',
    branchName:  'Branch Name',
    address:     'Address',
    phone:       'Phone',
    currency:    'Currency',
    taxRate:     'Tax Rate (%)',
    // Marketing
    campaigns:   'Campaigns',
    discounts:   'Discounts',
    promotions:  'Promotions',
    loyalty:     'Loyalty',
    addCampaign: 'Add Campaign',
    discount:    'Discount',
    startDate:   'Start Date',
    endDate:     'End Date',
    active:      'Active',
    inactive:    'Inactive',
  },
  uz: {
    dashboard:   'Bosh sahifa',
    pos:         'Kassa',
    products:    'Mahsulotlar',
    inventory:   'Ombor',
    customers:   'Mijozlar',
    orders:      'Buyurtmalar',
    finance:     'Moliya',
    marketing:   'Marketing',
    sellers:     'Sotuvchilar',
    branches:    'Filiallar',
    settings:    'Sozlamalar',
    save:        'Saqlash',
    cancel:      'Bekor qilish',
    edit:        'Tahrirlash',
    delete:      "O'chirish",
    add:         "Qo'shish",
    search:      'Qidirish',
    loading:     'Yuklanmoqda…',
    noData:      'Ma\'lumot topilmadi',
    confirm:     'Ishonchingiz komilmi?',
    addProduct:  'Mahsulot qo\'shish',
    productName: 'Mahsulot nomi',
    brand:       'Brend',
    category:    'Kategoriya',
    skuBase:     'SKU asosi',
    costPrice:   'Tannarx',
    sellPrice:   'Sotish narxi',
    description: 'Tavsif',
    variants:    'Variantlar',
    initialStock:'Boshlang\'ich qoldiq',
    addSeller:   'Sotuvchi qo\'shish',
    sellerName:  'To\'liq ism',
    email:       'Elektron pochta',
    role:        'Lavozim',
    branch:      'Filial',
    password:    'Parol',
    pin:         'PIN',
    addBranch:   'Filial qo\'shish',
    branchName:  'Filial nomi',
    address:     'Manzil',
    phone:       'Telefon',
    currency:    'Valyuta',
    taxRate:     'Soliq stavkasi (%)',
    campaigns:   'Kampaniyalar',
    discounts:   'Chegirmalar',
    promotions:  'Aktsiyalar',
    loyalty:     'Sodiqlik',
    addCampaign: 'Kampaniya qo\'shish',
    discount:    'Chegirma',
    startDate:   'Boshlanish sanasi',
    endDate:     'Tugash sanasi',
    active:      'Faol',
    inactive:    'Faol emas',
  },
  ru: {
    dashboard:   'Главная',
    pos:         'Касса',
    products:    'Товары',
    inventory:   'Склад',
    customers:   'Клиенты',
    orders:      'Заказы',
    finance:     'Финансы',
    marketing:   'Маркетинг',
    sellers:     'Продавцы',
    branches:    'Филиалы',
    settings:    'Настройки',
    save:        'Сохранить',
    cancel:      'Отмена',
    edit:        'Изменить',
    delete:      'Удалить',
    add:         'Добавить',
    search:      'Поиск',
    loading:     'Загрузка…',
    noData:      'Данные не найдены',
    confirm:     'Вы уверены?',
    addProduct:  'Добавить товар',
    productName: 'Название товара',
    brand:       'Бренд',
    category:    'Категория',
    skuBase:     'Базовый SKU',
    costPrice:   'Себестоимость',
    sellPrice:   'Цена продажи',
    description: 'Описание',
    variants:    'Варианты',
    initialStock:'Начальный остаток',
    addSeller:   'Добавить продавца',
    sellerName:  'Полное имя',
    email:       'Эл. почта',
    role:        'Роль',
    branch:      'Филиал',
    password:    'Пароль',
    pin:         'PIN',
    addBranch:   'Добавить филиал',
    branchName:  'Название филиала',
    address:     'Адрес',
    phone:       'Телефон',
    currency:    'Валюта',
    taxRate:     'Ставка налога (%)',
    campaigns:   'Кампании',
    discounts:   'Скидки',
    promotions:  'Акции',
    loyalty:     'Лояльность',
    addCampaign: 'Добавить кампанию',
    discount:    'Скидка',
    startDate:   'Дата начала',
    endDate:     'Дата окончания',
    active:      'Активна',
    inactive:    'Неактивна',
  },
}

interface LangState {
  lang:    Lang
  t:       typeof T.en
  setLang: (l: Lang) => void
}

export const useLang = create<LangState>()(
  persist(
    (set) => ({
      lang: 'en',
      t:    T.en,
      setLang: (l) => set({ lang: l, t: T[l] }),
    }),
    { name: 'avero-lang' }
  )
)
